// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                        string     `json:"id"`
	Name                      string     `json:"name"`
	ProjectID                 string     `json:"project_id"`
	HostingRegion             string     `json:"hosting_region"`
	Status                    string     `json:"status"`
	LastEdited                time.Time  `json:"last_edited"`
	LastPublished             *time.Time `json:"last_published"`
	Template                  string     `json:"template"`
	SystemPrompt              string     `json:"system_prompt"`
	GreetingMessage           string     `json:"greeting_message"`
	FailureMessage            string     `json:"failure_message"`
	ModelType                 string     `json:"model_type"`
	Asr                       []byte     `json:"asr"`
	Llm                       []byte     `json:"llm"`
	Tts                       []byte     `json:"tts"`
	TurnDetection             bool       `json:"turn_detection"`
	StartOfSpeech             bool       `json:"start_of_speech"`
	EndOfSpeech               bool       `json:"end_of_speech"`
	SelectiveAttentionLocking bool       `json:"selective_attention_locking"`
	FillerWords               bool       `json:"filler_words"`
	MaxHistory                int32      `json:"max_history"`
	McpServers                []byte     `json:"mcp_servers"`
	Skills                    []byte     `json:"skills"`
	SubAgents                 []byte     `json:"sub_agents"`
	ClarificationRules        []byte     `json:"clarification_rules"`
}

type ConversationState struct {
	ChatID            string    `json:"chat_id"`
	Summary           string    `json:"summary"`
	SummarizedThrough int64     `json:"summarized_through"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type ConversationTurn struct {
	ID      int64     `json:"id"`
	ChatID  string    `json:"chat_id"`
	Role    string    `json:"role"`
	Content string    `json:"content"`
	Ts      time.Time `json:"ts"`
}

type HealthCheck struct {
	ID        int32     `json:"id"`
	Note      string    `json:"note"`
	CheckedAt time.Time `json:"checked_at"`
}

type PendingConfirmation struct {
	ChatID        string     `json:"chat_id"`
	ToolID        string     `json:"tool_id"`
	Args          []byte     `json:"args"`
	OrgID         string     `json:"org_id"`
	ActingUserUid string     `json:"acting_user_uid"`
	Description   string     `json:"description"`
	Status        string     `json:"status"`
	ClaimedAt     *time.Time `json:"claimed_at"`
	CreatedAt     time.Time  `json:"created_at"`
	ExpiresAt     time.Time  `json:"expires_at"`
	MissingFields []byte     `json:"missing_fields"`
	CollectRounds int32      `json:"collect_rounds"`
	Intent        string     `json:"intent"`
}

type ProcessedMessage struct {
	ID          string    `json:"id"`
	ProcessedAt time.Time `json:"processed_at"`
}

type Setting struct {
	ID               int32   `json:"id"`
	TtsModel         string  `json:"tts_model"`
	ModelIds         []byte  `json:"model_ids"`
	DefaultSpeed     float32 `json:"default_speed"`
	BotConfig        []byte  `json:"bot_config"`
	AssistantAgentID *string `json:"assistant_agent_id"`
}

type SttHistory struct {
	ID         string    `json:"id"`
	Ts         time.Time `json:"ts"`
	Transcript string    `json:"transcript"`
	Filename   string    `json:"filename"`
	DurationMs int32     `json:"duration_ms"`
	Language   string    `json:"language"`
}

type ToolExecution struct {
	ID     int64     `json:"id"`
	ChatID string    `json:"chat_id"`
	ToolID string    `json:"tool_id"`
	Args   []byte    `json:"args"`
	Result []byte    `json:"result"`
	Status string    `json:"status"`
	Ts     time.Time `json:"ts"`
}

type TtsHistory struct {
	ID         string    `json:"id"`
	Ts         time.Time `json:"ts"`
	Text       string    `json:"text"`
	Model      string    `json:"model"`
	Speed      float32   `json:"speed"`
	DurationMs int32     `json:"duration_ms"`
	SizeBytes  int32     `json:"size_bytes"`
}

type User struct {
	ID           int32     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type WaActivity struct {
	ID          string    `json:"id"`
	Ts          time.Time `json:"ts"`
	ChatID      string    `json:"chat_id"`
	ContactName string    `json:"contact_name"`
	Direction   string    `json:"direction"`
	MsgType     string    `json:"msg_type"`
	Transcript  string    `json:"transcript"`
	Reply       string    `json:"reply"`
	Language    string    `json:"language"`
	AgentID     *string   `json:"agent_id"`
	LlmModel    *string   `json:"llm_model"`
	TtsModel    *string   `json:"tts_model"`
	ToolCalls   []byte    `json:"tool_calls"`
	SttMs       int32     `json:"stt_ms"`
	LlmMs       int32     `json:"llm_ms"`
	TtsMs       int32     `json:"tts_ms"`
	TotalMs     int32     `json:"total_ms"`
	Status      string    `json:"status"`
	Error       *string   `json:"error"`
}

type WaContact struct {
	ChatID         string    `json:"chat_id"`
	Name           string    `json:"name"`
	Enabled        bool      `json:"enabled"`
	AgentID        *string   `json:"agent_id"`
	PromptOverride *string   `json:"prompt_override"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type WaMessage struct {
	ID        string      `json:"id"`
	Seq       pgtype.Int8 `json:"seq"`
	ChatID    string      `json:"chat_id"`
	Direction string      `json:"direction"`
	Sender    string      `json:"sender"`
	MsgType   string      `json:"msg_type"`
	Content   string      `json:"content"`
	Status    string      `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
}

type WaVoiceNote struct {
	ID              string     `json:"id"`
	ChatID          string     `json:"chat_id"`
	Direction       string     `json:"direction"`
	Sender          string     `json:"sender"`
	Receiver        string     `json:"receiver"`
	ObjectPath      string     `json:"object_path"`
	MimeType        string     `json:"mime_type"`
	SizeBytes       int64      `json:"size_bytes"`
	DurationSeconds int32      `json:"duration_seconds"`
	Status          string     `json:"status"`
	Attempts        int32      `json:"attempts"`
	NextAttemptAt   time.Time  `json:"next_attempt_at"`
	LastError       *string    `json:"last_error"`
	CreatedAt       time.Time  `json:"created_at"`
	UploadedAt      *time.Time `json:"uploaded_at"`
}

type WebhookLog struct {
	ID           string    `json:"id"`
	Type         string    `json:"type"`
	Ts           time.Time `json:"ts"`
	Status       int32     `json:"status"`
	InputPreview string    `json:"input_preview"`
	DurationMs   int32     `json:"duration_ms"`
}
