// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingConfirmation = `-- name: ClaimPendingConfirmation :one
UPDATE pending_confirmations
SET status = 'executing', claimed_at = NOW()
WHERE chat_id = $1 AND status = 'pending'
RETURNING chat_id, tool_id, args, org_id, acting_user_uid, description, status, claimed_at, created_at, expires_at
`

// ClaimPendingConfirmation atomically transitions a chat's pending row to
// 'executing' and returns it. Because the UPDATE matches only status='pending',
// exactly one of two concurrent resolvers wins the row; the loser gets no row.
// This is the guard against double-executing a confirmed (financial) tool.
func (q *Queries) ClaimPendingConfirmation(ctx context.Context, chatID string) (PendingConfirmation, error) {
	row := q.db.QueryRow(ctx, claimPendingConfirmation, chatID)
	var i PendingConfirmation
	err := row.Scan(
		&i.ChatID,
		&i.ToolID,
		&i.Args,
		&i.OrgID,
		&i.ActingUserUid,
		&i.Description,
		&i.Status,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    id, name, project_id, hosting_region, status, last_edited,
    last_published, template, system_prompt, greeting_message,
    failure_message, model_type, asr, llm, tts, turn_detection,
    start_of_speech, end_of_speech, selective_attention_locking,
    filler_words, max_history, mcp_servers, skills, sub_agents
) VALUES (
    $1, $2, $3, $4, $5, NOW(),
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15,
    $16, $17, $18,
    $19, $20, $21, $22, $23
) RETURNING id, name, project_id, hosting_region, status, last_edited, last_published, template, system_prompt, greeting_message, failure_message, model_type, asr, llm, tts, turn_detection, start_of_speech, end_of_speech, selective_attention_locking, filler_words, max_history, mcp_servers, skills, sub_agents
`

type CreateAgentParams struct {
	ID                        string     `json:"id"`
	Name                      string     `json:"name"`
	ProjectID                 string     `json:"project_id"`
	HostingRegion             string     `json:"hosting_region"`
	Status                    string     `json:"status"`
	LastPublished             *time.Time `json:"last_published"`
	Template                  string     `json:"template"`
	SystemPrompt              string     `json:"system_prompt"`
	GreetingMessage           string     `json:"greeting_message"`
	FailureMessage            string     `json:"failure_message"`
	ModelType                 string     `json:"model_type"`
	Asr                       []byte     `json:"asr"`
	Llm                       []byte     `json:"llm"`
	Tts                       []byte     `json:"tts"`
	TurnDetection             bool       `json:"turn_detection"`
	StartOfSpeech             bool       `json:"start_of_speech"`
	EndOfSpeech               bool       `json:"end_of_speech"`
	SelectiveAttentionLocking bool       `json:"selective_attention_locking"`
	FillerWords               bool       `json:"filler_words"`
	MaxHistory                int32      `json:"max_history"`
	McpServers                []byte     `json:"mcp_servers"`
	Skills                    []byte     `json:"skills"`
	SubAgents                 []byte     `json:"sub_agents"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.ProjectID,
		arg.HostingRegion,
		arg.Status,
		arg.LastPublished,
		arg.Template,
		arg.SystemPrompt,
		arg.GreetingMessage,
		arg.FailureMessage,
		arg.ModelType,
		arg.Asr,
		arg.Llm,
		arg.Tts,
		arg.TurnDetection,
		arg.StartOfSpeech,
		arg.EndOfSpeech,
		arg.SelectiveAttentionLocking,
		arg.FillerWords,
		arg.MaxHistory,
		arg.McpServers,
		arg.Skills,
		arg.SubAgents,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.HostingRegion,
		&i.Status,
		&i.LastEdited,
		&i.LastPublished,
		&i.Template,
		&i.SystemPrompt,
		&i.GreetingMessage,
		&i.FailureMessage,
		&i.ModelType,
		&i.Asr,
		&i.Llm,
		&i.Tts,
		&i.TurnDetection,
		&i.StartOfSpeech,
		&i.EndOfSpeech,
		&i.SelectiveAttentionLocking,
		&i.FillerWords,
		&i.MaxHistory,
		&i.McpServers,
		&i.Skills,
		&i.SubAgents,
	)
	return i, err
}

const createConversationTurn = `-- name: CreateConversationTurn :one
INSERT INTO conversation_turns (chat_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, chat_id, role, content, ts
`

type CreateConversationTurnParams struct {
	ChatID  string `json:"chat_id"`
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (q *Queries) CreateConversationTurn(ctx context.Context, arg CreateConversationTurnParams) (ConversationTurn, error) {
	row := q.db.QueryRow(ctx, createConversationTurn, arg.ChatID, arg.Role, arg.Content)
	var i ConversationTurn
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Content,
		&i.Ts,
	)
	return i, err
}

const createOrUpdateWaContact = `-- name: CreateOrUpdateWaContact :one
INSERT INTO wa_contacts (chat_id, name, enabled, agent_id, prompt_override, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (chat_id) DO UPDATE
SET name = EXCLUDED.name, enabled = EXCLUDED.enabled, agent_id = EXCLUDED.agent_id,
    prompt_override = EXCLUDED.prompt_override, updated_at = NOW()
RETURNING chat_id, name, enabled, agent_id, prompt_override, updated_at
`

type CreateOrUpdateWaContactParams struct {
	ChatID         string  `json:"chat_id"`
	Name           string  `json:"name"`
	Enabled        bool    `json:"enabled"`
	AgentID        *string `json:"agent_id"`
	PromptOverride *string `json:"prompt_override"`
}

func (q *Queries) CreateOrUpdateWaContact(ctx context.Context, arg CreateOrUpdateWaContactParams) (WaContact, error) {
	row := q.db.QueryRow(ctx, createOrUpdateWaContact,
		arg.ChatID,
		arg.Name,
		arg.Enabled,
		arg.AgentID,
		arg.PromptOverride,
	)
	var i WaContact
	err := row.Scan(
		&i.ChatID,
		&i.Name,
		&i.Enabled,
		&i.AgentID,
		&i.PromptOverride,
		&i.UpdatedAt,
	)
	return i, err
}

const createSttHistory = `-- name: CreateSttHistory :exec
INSERT INTO stt_history (id, ts, transcript, filename, duration_ms, language)
VALUES ($1, NOW(), $2, $3, $4, $5)
`

type CreateSttHistoryParams struct {
	ID         string `json:"id"`
	Transcript string `json:"transcript"`
	Filename   string `json:"filename"`
	DurationMs int32  `json:"duration_ms"`
	Language   string `json:"language"`
}

func (q *Queries) CreateSttHistory(ctx context.Context, arg CreateSttHistoryParams) error {
	_, err := q.db.Exec(ctx, createSttHistory,
		arg.ID,
		arg.Transcript,
		arg.Filename,
		arg.DurationMs,
		arg.Language,
	)
	return err
}

const createToolExecution = `-- name: CreateToolExecution :exec
INSERT INTO tool_executions (chat_id, tool_id, args, result, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateToolExecutionParams struct {
	ChatID string `json:"chat_id"`
	ToolID string `json:"tool_id"`
	Args   []byte `json:"args"`
	Result []byte `json:"result"`
	Status string `json:"status"`
}

func (q *Queries) CreateToolExecution(ctx context.Context, arg CreateToolExecutionParams) error {
	_, err := q.db.Exec(ctx, createToolExecution,
		arg.ChatID,
		arg.ToolID,
		arg.Args,
		arg.Result,
		arg.Status,
	)
	return err
}

const createTtsHistory = `-- name: CreateTtsHistory :exec
INSERT INTO tts_history (id, ts, text, model, speed, duration_ms, size_bytes)
VALUES ($1, NOW(), $2, $3, $4, $5, $6)
`

type CreateTtsHistoryParams struct {
	ID         string  `json:"id"`
	Text       string  `json:"text"`
	Model      string  `json:"model"`
	Speed      float32 `json:"speed"`
	DurationMs int32   `json:"duration_ms"`
	SizeBytes  int32   `json:"size_bytes"`
}

func (q *Queries) CreateTtsHistory(ctx context.Context, arg CreateTtsHistoryParams) error {
	_, err := q.db.Exec(ctx, createTtsHistory,
		arg.ID,
		arg.Text,
		arg.Model,
		arg.Speed,
		arg.DurationMs,
		arg.SizeBytes,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, created_at)
VALUES ($1, $2, NOW())
RETURNING id, username, password_hash, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createWaActivity = `-- name: CreateWaActivity :exec
INSERT INTO wa_activity (
    id, ts, chat_id, contact_name, direction, msg_type, transcript, 
    reply, language, agent_id, llm_model, tts_model, tool_calls, 
    stt_ms, llm_ms, tts_ms, total_ms, status, error
) VALUES (
    $1, NOW(), $2, $3, $4, $5, $6, 
    $7, $8, $9, $10, $11, $12, 
    $13, $14, $15, $16, $17, $18
)
`

type CreateWaActivityParams struct {
	ID          string  `json:"id"`
	ChatID      string  `json:"chat_id"`
	ContactName string  `json:"contact_name"`
	Direction   string  `json:"direction"`
	MsgType     string  `json:"msg_type"`
	Transcript  string  `json:"transcript"`
	Reply       string  `json:"reply"`
	Language    string  `json:"language"`
	AgentID     *string `json:"agent_id"`
	LlmModel    *string `json:"llm_model"`
	TtsModel    *string `json:"tts_model"`
	ToolCalls   []byte  `json:"tool_calls"`
	SttMs       int32   `json:"stt_ms"`
	LlmMs       int32   `json:"llm_ms"`
	TtsMs       int32   `json:"tts_ms"`
	TotalMs     int32   `json:"total_ms"`
	Status      string  `json:"status"`
	Error       *string `json:"error"`
}

func (q *Queries) CreateWaActivity(ctx context.Context, arg CreateWaActivityParams) error {
	_, err := q.db.Exec(ctx, createWaActivity,
		arg.ID,
		arg.ChatID,
		arg.ContactName,
		arg.Direction,
		arg.MsgType,
		arg.Transcript,
		arg.Reply,
		arg.Language,
		arg.AgentID,
		arg.LlmModel,
		arg.TtsModel,
		arg.ToolCalls,
		arg.SttMs,
		arg.LlmMs,
		arg.TtsMs,
		arg.TotalMs,
		arg.Status,
		arg.Error,
	)
	return err
}

const createWaMessage = `-- name: CreateWaMessage :exec
INSERT INTO wa_messages (id, chat_id, direction, sender, msg_type, content, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateWaMessageParams struct {
	ID        string `json:"id"`
	ChatID    string `json:"chat_id"`
	Direction string `json:"direction"`
	Sender    string `json:"sender"`
	MsgType   string `json:"msg_type"`
	Content   string `json:"content"`
	Status    string `json:"status"`
}

func (q *Queries) CreateWaMessage(ctx context.Context, arg CreateWaMessageParams) error {
	_, err := q.db.Exec(ctx, createWaMessage,
		arg.ID,
		arg.ChatID,
		arg.Direction,
		arg.Sender,
		arg.MsgType,
		arg.Content,
		arg.Status,
	)
	return err
}

const createWebhookLog = `-- name: CreateWebhookLog :exec
INSERT INTO webhook_logs (id, type, ts, status, input_preview, duration_ms)
VALUES ($1, $2, NOW(), $3, $4, $5)
`

type CreateWebhookLogParams struct {
	ID           string `json:"id"`
	Type         string `json:"type"`
	Status       int32  `json:"status"`
	InputPreview string `json:"input_preview"`
	DurationMs   int32  `json:"duration_ms"`
}

func (q *Queries) CreateWebhookLog(ctx context.Context, arg CreateWebhookLogParams) error {
	_, err := q.db.Exec(ctx, createWebhookLog,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.InputPreview,
		arg.DurationMs,
	)
	return err
}

const deletePendingConfirmation = `-- name: DeletePendingConfirmation :exec
DELETE FROM pending_confirmations WHERE chat_id = $1
`

func (q *Queries) DeletePendingConfirmation(ctx context.Context, chatID string) error {
	_, err := q.db.Exec(ctx, deletePendingConfirmation, chatID)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, project_id, hosting_region, status, last_edited, last_published, template, system_prompt, greeting_message, failure_message, model_type, asr, llm, tts, turn_detection, start_of_speech, end_of_speech, selective_attention_locking, filler_words, max_history, mcp_servers, skills, sub_agents FROM agents
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.HostingRegion,
		&i.Status,
		&i.LastEdited,
		&i.LastPublished,
		&i.Template,
		&i.SystemPrompt,
		&i.GreetingMessage,
		&i.FailureMessage,
		&i.ModelType,
		&i.Asr,
		&i.Llm,
		&i.Tts,
		&i.TurnDetection,
		&i.StartOfSpeech,
		&i.EndOfSpeech,
		&i.SelectiveAttentionLocking,
		&i.FillerWords,
		&i.MaxHistory,
		&i.McpServers,
		&i.Skills,
		&i.SubAgents,
	)
	return i, err
}

const getConversationState = `-- name: GetConversationState :one
SELECT chat_id, summary, summarized_through, updated_at FROM conversation_state
WHERE chat_id = $1
`

func (q *Queries) GetConversationState(ctx context.Context, chatID string) (ConversationState, error) {
	row := q.db.QueryRow(ctx, getConversationState, chatID)
	var i ConversationState
	err := row.Scan(
		&i.ChatID,
		&i.Summary,
		&i.SummarizedThrough,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingConfirmation = `-- name: GetPendingConfirmation :one
SELECT chat_id, tool_id, args, org_id, acting_user_uid, description, status, claimed_at, created_at, expires_at FROM pending_confirmations
WHERE chat_id = $1
`

func (q *Queries) GetPendingConfirmation(ctx context.Context, chatID string) (PendingConfirmation, error) {
	row := q.db.QueryRow(ctx, getPendingConfirmation, chatID)
	var i PendingConfirmation
	err := row.Scan(
		&i.ChatID,
		&i.ToolID,
		&i.Args,
		&i.OrgID,
		&i.ActingUserUid,
		&i.Description,
		&i.Status,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT id, tts_model, model_ids, default_speed, bot_config, assistant_agent_id FROM settings
ORDER BY id LIMIT 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.TtsModel,
		&i.ModelIds,
		&i.DefaultSpeed,
		&i.BotConfig,
		&i.AssistantAgentID,
	)
	return i, err
}

const getSttHistory = `-- name: GetSttHistory :many
SELECT id, ts, transcript, filename, duration_ms, language FROM stt_history
ORDER BY ts DESC LIMIT $1
`

func (q *Queries) GetSttHistory(ctx context.Context, limit int32) ([]SttHistory, error) {
	rows, err := q.db.Query(ctx, getSttHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SttHistory
	for rows.Next() {
		var i SttHistory
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Transcript,
			&i.Filename,
			&i.DurationMs,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTtsHistory = `-- name: GetTtsHistory :many
SELECT id, ts, text, model, speed, duration_ms, size_bytes FROM tts_history
ORDER BY ts DESC LIMIT $1
`

func (q *Queries) GetTtsHistory(ctx context.Context, limit int32) ([]TtsHistory, error) {
	rows, err := q.db.Query(ctx, getTtsHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TtsHistory
	for rows.Next() {
		var i TtsHistory
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Text,
			&i.Model,
			&i.Speed,
			&i.DurationMs,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getWaContact = `-- name: GetWaContact :one
SELECT chat_id, name, enabled, agent_id, prompt_override, updated_at FROM wa_contacts
WHERE chat_id = $1 LIMIT 1
`

func (q *Queries) GetWaContact(ctx context.Context, chatID string) (WaContact, error) {
	row := q.db.QueryRow(ctx, getWaContact, chatID)
	var i WaContact
	err := row.Scan(
		&i.ChatID,
		&i.Name,
		&i.Enabled,
		&i.AgentID,
		&i.PromptOverride,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, project_id, hosting_region, status, last_edited, last_published, template, system_prompt, greeting_message, failure_message, model_type, asr, llm, tts, turn_detection, start_of_speech, end_of_speech, selective_attention_locking, filler_words, max_history, mcp_servers, skills, sub_agents FROM agents
ORDER BY name
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.HostingRegion,
			&i.Status,
			&i.LastEdited,
			&i.LastPublished,
			&i.Template,
			&i.SystemPrompt,
			&i.GreetingMessage,
			&i.FailureMessage,
			&i.ModelType,
			&i.Asr,
			&i.Llm,
			&i.Tts,
			&i.TurnDetection,
			&i.StartOfSpeech,
			&i.EndOfSpeech,
			&i.SelectiveAttentionLocking,
			&i.FillerWords,
			&i.MaxHistory,
			&i.McpServers,
			&i.Skills,
			&i.SubAgents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationTurnsAfter = `-- name: ListConversationTurnsAfter :many
SELECT id, chat_id, role, content, ts FROM conversation_turns
WHERE chat_id = $1 AND id > $2::bigint
ORDER BY id ASC
LIMIT $3::int
`

type ListConversationTurnsAfterParams struct {
	ChatID  string `json:"chat_id"`
	AfterID int64  `json:"after_id"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListConversationTurnsAfter(ctx context.Context, arg ListConversationTurnsAfterParams) ([]ConversationTurn, error) {
	rows, err := q.db.Query(ctx, listConversationTurnsAfter, arg.ChatID, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationTurn
	for rows.Next() {
		var i ConversationTurn
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Content,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWaVoiceNotes = `-- name: ListPendingWaVoiceNotes :many
SELECT id, chat_id, direction, sender, receiver, object_path, mime_type, size_bytes, duration_seconds, status, attempts, next_attempt_at, last_error, created_at, uploaded_at FROM wa_voice_notes
WHERE status = 'pending' AND next_attempt_at <= NOW()
ORDER BY next_attempt_at ASC
LIMIT $1
`

func (q *Queries) ListPendingWaVoiceNotes(ctx context.Context, limit int32) ([]WaVoiceNote, error) {
	rows, err := q.db.Query(ctx, listPendingWaVoiceNotes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaVoiceNote
	for rows.Next() {
		var i WaVoiceNote
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Direction,
			&i.Sender,
			&i.Receiver,
			&i.ObjectPath,
			&i.MimeType,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedAgents = `-- name: ListPublishedAgents :many
SELECT id, name, project_id, hosting_region, status, last_edited, last_published, template, system_prompt, greeting_message, failure_message, model_type, asr, llm, tts, turn_detection, start_of_speech, end_of_speech, selective_attention_locking, filler_words, max_history, mcp_servers, skills, sub_agents FROM agents
WHERE status = 'published'
ORDER BY name
`

func (q *Queries) ListPublishedAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listPublishedAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.HostingRegion,
			&i.Status,
			&i.LastEdited,
			&i.LastPublished,
			&i.Template,
			&i.SystemPrompt,
			&i.GreetingMessage,
			&i.FailureMessage,
			&i.ModelType,
			&i.Asr,
			&i.Llm,
			&i.Tts,
			&i.TurnDetection,
			&i.StartOfSpeech,
			&i.EndOfSpeech,
			&i.SelectiveAttentionLocking,
			&i.FillerWords,
			&i.MaxHistory,
			&i.McpServers,
			&i.Skills,
			&i.SubAgents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentWaActivity = `-- name: ListRecentWaActivity :many
SELECT id, ts, chat_id, contact_name, direction, msg_type, transcript, reply, language, agent_id, llm_model, tts_model, tool_calls, stt_ms, llm_ms, tts_ms, total_ms, status, error FROM wa_activity
ORDER BY ts DESC LIMIT $1
`

func (q *Queries) ListRecentWaActivity(ctx context.Context, limit int32) ([]WaActivity, error) {
	rows, err := q.db.Query(ctx, listRecentWaActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaActivity
	for rows.Next() {
		var i WaActivity
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ChatID,
			&i.ContactName,
			&i.Direction,
			&i.MsgType,
			&i.Transcript,
			&i.Reply,
			&i.Language,
			&i.AgentID,
			&i.LlmModel,
			&i.TtsModel,
			&i.ToolCalls,
			&i.SttMs,
			&i.LlmMs,
			&i.TtsMs,
			&i.TotalMs,
			&i.Status,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaChatsSummary = `-- name: ListWaChatsSummary :many
SELECT chat_id, last_message, last_direction, last_sender, last_message_at, contact_name, contact_enabled, contact_agent_id FROM (
    SELECT DISTINCT ON (m.chat_id)
        m.chat_id, m.content AS last_message, m.direction AS last_direction,
        m.sender AS last_sender, m.created_at AS last_message_at,
        c.name AS contact_name, c.enabled AS contact_enabled, c.agent_id AS contact_agent_id
    FROM wa_messages m
    LEFT JOIN wa_contacts c ON c.chat_id = m.chat_id
    ORDER BY m.chat_id, m.created_at DESC, m.id DESC
) t
ORDER BY last_message_at DESC
`

type ListWaChatsSummaryRow struct {
	ChatID         string      `json:"chat_id"`
	LastMessage    string      `json:"last_message"`
	LastDirection  string      `json:"last_direction"`
	LastSender     string      `json:"last_sender"`
	LastMessageAt  time.Time   `json:"last_message_at"`
	ContactName    *string     `json:"contact_name"`
	ContactEnabled pgtype.Bool `json:"contact_enabled"`
	ContactAgentID *string     `json:"contact_agent_id"`
}

func (q *Queries) ListWaChatsSummary(ctx context.Context) ([]ListWaChatsSummaryRow, error) {
	rows, err := q.db.Query(ctx, listWaChatsSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWaChatsSummaryRow
	for rows.Next() {
		var i ListWaChatsSummaryRow
		if err := rows.Scan(
			&i.ChatID,
			&i.LastMessage,
			&i.LastDirection,
			&i.LastSender,
			&i.LastMessageAt,
			&i.ContactName,
			&i.ContactEnabled,
			&i.ContactAgentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaContacts = `-- name: ListWaContacts :many
SELECT chat_id, name, enabled, agent_id, prompt_override, updated_at FROM wa_contacts
ORDER BY updated_at DESC
`

func (q *Queries) ListWaContacts(ctx context.Context) ([]WaContact, error) {
	rows, err := q.db.Query(ctx, listWaContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaContact
	for rows.Next() {
		var i WaContact
		if err := rows.Scan(
			&i.ChatID,
			&i.Name,
			&i.Enabled,
			&i.AgentID,
			&i.PromptOverride,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaMessagesByChat = `-- name: ListWaMessagesByChat :many
SELECT id, seq, chat_id, direction, sender, msg_type, content, status, created_at FROM wa_messages
WHERE chat_id = $1 AND ($2::bigint = 0 OR seq < $2::bigint)
ORDER BY seq DESC LIMIT $3::int
`

type ListWaMessagesByChatParams struct {
	ChatID    string `json:"chat_id"`
	BeforeSeq int64  `json:"before_seq"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListWaMessagesByChat(ctx context.Context, arg ListWaMessagesByChatParams) ([]WaMessage, error) {
	rows, err := q.db.Query(ctx, listWaMessagesByChat, arg.ChatID, arg.BeforeSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaMessage
	for rows.Next() {
		var i WaMessage
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ChatID,
			&i.Direction,
			&i.Sender,
			&i.MsgType,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageProcessed = `-- name: MarkMessageProcessed :one
INSERT INTO processed_messages (id) VALUES ($1)
ON CONFLICT (id) DO NOTHING
RETURNING id
`

func (q *Queries) MarkMessageProcessed(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, markMessageProcessed, id)
	err := row.Scan(&id)
	return id, err
}

const markWaVoiceNoteFailed = `-- name: MarkWaVoiceNoteFailed :exec
UPDATE wa_voice_notes
SET attempts = attempts + 1,
    last_error = $2,
    next_attempt_at = $3,
    status = CASE WHEN attempts + 1 >= $4 THEN 'failed' ELSE 'pending' END
WHERE id = $1
`

type MarkWaVoiceNoteFailedParams struct {
	ID            string    `json:"id"`
	LastError     *string   `json:"last_error"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	MaxAttempts   int32     `json:"max_attempts"`
}

// Failure keeps the row 'pending' (retryable) until attempts reaches the cap,
// then flips it to the terminal 'failed'. next_attempt_at carries the
// caller-computed exponential backoff.
func (q *Queries) MarkWaVoiceNoteFailed(ctx context.Context, arg MarkWaVoiceNoteFailedParams) error {
	_, err := q.db.Exec(ctx, markWaVoiceNoteFailed,
		arg.ID,
		arg.LastError,
		arg.NextAttemptAt,
		arg.MaxAttempts,
	)
	return err
}

const markWaVoiceNoteUploaded = `-- name: MarkWaVoiceNoteUploaded :exec
UPDATE wa_voice_notes
SET status = 'uploaded', uploaded_at = NOW(), last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkWaVoiceNoteUploaded(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markWaVoiceNoteUploaded, id)
	return err
}

const purgeConversationTurnsBefore = `-- name: PurgeConversationTurnsBefore :exec
DELETE FROM conversation_turns WHERE ts < $1
`

func (q *Queries) PurgeConversationTurnsBefore(ctx context.Context, ts time.Time) error {
	_, err := q.db.Exec(ctx, purgeConversationTurnsBefore, ts)
	return err
}

const purgeExpiredConfirmations = `-- name: PurgeExpiredConfirmations :exec
DELETE FROM pending_confirmations WHERE expires_at < $1
`

func (q *Queries) PurgeExpiredConfirmations(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, purgeExpiredConfirmations, expiresAt)
	return err
}

const purgeProcessedMessagesBefore = `-- name: PurgeProcessedMessagesBefore :exec
DELETE FROM processed_messages WHERE processed_at < $1
`

func (q *Queries) PurgeProcessedMessagesBefore(ctx context.Context, processedAt time.Time) error {
	_, err := q.db.Exec(ctx, purgeProcessedMessagesBefore, processedAt)
	return err
}

const purgeSttHistoryBefore = `-- name: PurgeSttHistoryBefore :exec
DELETE FROM stt_history WHERE ts < $1
`

func (q *Queries) PurgeSttHistoryBefore(ctx context.Context, ts time.Time) error {
	_, err := q.db.Exec(ctx, purgeSttHistoryBefore, ts)
	return err
}

const purgeToolExecutionsBefore = `-- name: PurgeToolExecutionsBefore :exec
DELETE FROM tool_executions WHERE ts < $1
`

func (q *Queries) PurgeToolExecutionsBefore(ctx context.Context, ts time.Time) error {
	_, err := q.db.Exec(ctx, purgeToolExecutionsBefore, ts)
	return err
}

const purgeTtsHistoryBefore = `-- name: PurgeTtsHistoryBefore :exec
DELETE FROM tts_history WHERE ts < $1
`

func (q *Queries) PurgeTtsHistoryBefore(ctx context.Context, ts time.Time) error {
	_, err := q.db.Exec(ctx, purgeTtsHistoryBefore, ts)
	return err
}

const purgeWaVoiceNotesBefore = `-- name: PurgeWaVoiceNotesBefore :exec
DELETE FROM wa_voice_notes WHERE created_at < $1
`

func (q *Queries) PurgeWaVoiceNotesBefore(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, purgeWaVoiceNotesBefore, createdAt)
	return err
}

const redactWaActivityBefore = `-- name: RedactWaActivityBefore :exec
UPDATE wa_activity
SET transcript = '[redacted]', reply = '[redacted]'
WHERE ts < $1 AND transcript <> '[redacted]'
`

func (q *Queries) RedactWaActivityBefore(ctx context.Context, ts time.Time) error {
	_, err := q.db.Exec(ctx, redactWaActivityBefore, ts)
	return err
}

const redactWaMessagesBefore = `-- name: RedactWaMessagesBefore :exec
UPDATE wa_messages
SET content = '[redacted]'
WHERE created_at < $1 AND content <> '[redacted]'
`

func (q *Queries) RedactWaMessagesBefore(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, redactWaMessagesBefore, createdAt)
	return err
}

const updateAgentWorkflow = `-- name: UpdateAgentWorkflow :one
UPDATE agents
SET name = $2, system_prompt = $3, greeting_message = $4, failure_message = $5,
    asr = $6, llm = $7, tts = $8, max_history = $9,
    mcp_servers = $11, skills = $12, sub_agents = $13,
    turn_detection = $14, start_of_speech = $15, end_of_speech = $16,
    selective_attention_locking = $17, filler_words = $18,
    last_published = CASE WHEN $10::text = 'published' AND status <> 'published' THEN NOW() ELSE last_published END,
    status = $10, last_edited = NOW()
WHERE id = $1
RETURNING id, name, project_id, hosting_region, status, last_edited, last_published, template, system_prompt, greeting_message, failure_message, model_type, asr, llm, tts, turn_detection, start_of_speech, end_of_speech, selective_attention_locking, filler_words, max_history, mcp_servers, skills, sub_agents
`

type UpdateAgentWorkflowParams struct {
	ID                        string `json:"id"`
	Name                      string `json:"name"`
	SystemPrompt              string `json:"system_prompt"`
	GreetingMessage           string `json:"greeting_message"`
	FailureMessage            string `json:"failure_message"`
	Asr                       []byte `json:"asr"`
	Llm                       []byte `json:"llm"`
	Tts                       []byte `json:"tts"`
	MaxHistory                int32  `json:"max_history"`
	Status                    string `json:"status"`
	McpServers                []byte `json:"mcp_servers"`
	Skills                    []byte `json:"skills"`
	SubAgents                 []byte `json:"sub_agents"`
	TurnDetection             bool   `json:"turn_detection"`
	StartOfSpeech             bool   `json:"start_of_speech"`
	EndOfSpeech               bool   `json:"end_of_speech"`
	SelectiveAttentionLocking bool   `json:"selective_attention_locking"`
	FillerWords               bool   `json:"filler_words"`
}

// last_published is stamped only on the draft->published transition (D4);
// the CASE reads the pre-update status, per UPDATE..SET semantics. The panel
// now edits the full four-block config, so every operator-editable column is set.
func (q *Queries) UpdateAgentWorkflow(ctx context.Context, arg UpdateAgentWorkflowParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentWorkflow,
		arg.ID,
		arg.Name,
		arg.SystemPrompt,
		arg.GreetingMessage,
		arg.FailureMessage,
		arg.Asr,
		arg.Llm,
		arg.Tts,
		arg.MaxHistory,
		arg.Status,
		arg.McpServers,
		arg.Skills,
		arg.SubAgents,
		arg.TurnDetection,
		arg.StartOfSpeech,
		arg.EndOfSpeech,
		arg.SelectiveAttentionLocking,
		arg.FillerWords,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.HostingRegion,
		&i.Status,
		&i.LastEdited,
		&i.LastPublished,
		&i.Template,
		&i.SystemPrompt,
		&i.GreetingMessage,
		&i.FailureMessage,
		&i.ModelType,
		&i.Asr,
		&i.Llm,
		&i.Tts,
		&i.TurnDetection,
		&i.StartOfSpeech,
		&i.EndOfSpeech,
		&i.SelectiveAttentionLocking,
		&i.FillerWords,
		&i.MaxHistory,
		&i.McpServers,
		&i.Skills,
		&i.SubAgents,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings
SET tts_model = $1, model_ids = $2, default_speed = $3, bot_config = $4, assistant_agent_id = $5
WHERE id = 1
`

type UpdateSettingsParams struct {
	TtsModel         string  `json:"tts_model"`
	ModelIds         []byte  `json:"model_ids"`
	DefaultSpeed     float32 `json:"default_speed"`
	BotConfig        []byte  `json:"bot_config"`
	AssistantAgentID *string `json:"assistant_agent_id"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSettings,
		arg.TtsModel,
		arg.ModelIds,
		arg.DefaultSpeed,
		arg.BotConfig,
		arg.AssistantAgentID,
	)
	return err
}

const updateWaContactSettings = `-- name: UpdateWaContactSettings :one
UPDATE wa_contacts
SET enabled = $2, agent_id = $3, updated_at = NOW()
WHERE chat_id = $1
RETURNING chat_id, name, enabled, agent_id, prompt_override, updated_at
`

type UpdateWaContactSettingsParams struct {
	ChatID  string  `json:"chat_id"`
	Enabled bool    `json:"enabled"`
	AgentID *string `json:"agent_id"`
}

func (q *Queries) UpdateWaContactSettings(ctx context.Context, arg UpdateWaContactSettingsParams) (WaContact, error) {
	row := q.db.QueryRow(ctx, updateWaContactSettings, arg.ChatID, arg.Enabled, arg.AgentID)
	var i WaContact
	err := row.Scan(
		&i.ChatID,
		&i.Name,
		&i.Enabled,
		&i.AgentID,
		&i.PromptOverride,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConversationState = `-- name: UpsertConversationState :exec
INSERT INTO conversation_state (chat_id, summary, summarized_through, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (chat_id) DO UPDATE
SET summary = EXCLUDED.summary, summarized_through = EXCLUDED.summarized_through, updated_at = NOW()
`

type UpsertConversationStateParams struct {
	ChatID            string `json:"chat_id"`
	Summary           string `json:"summary"`
	SummarizedThrough int64  `json:"summarized_through"`
}

func (q *Queries) UpsertConversationState(ctx context.Context, arg UpsertConversationStateParams) error {
	_, err := q.db.Exec(ctx, upsertConversationState, arg.ChatID, arg.Summary, arg.SummarizedThrough)
	return err
}

const upsertPendingConfirmation = `-- name: UpsertPendingConfirmation :exec
INSERT INTO pending_confirmations (chat_id, tool_id, args, org_id, acting_user_uid, description, status, claimed_at, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', NULL, NOW(), $7)
ON CONFLICT (chat_id) DO UPDATE
SET tool_id = EXCLUDED.tool_id, args = EXCLUDED.args, org_id = EXCLUDED.org_id,
    acting_user_uid = EXCLUDED.acting_user_uid, description = EXCLUDED.description,
    status = 'pending', claimed_at = NULL,
    created_at = NOW(), expires_at = EXCLUDED.expires_at
`

type UpsertPendingConfirmationParams struct {
	ChatID        string    `json:"chat_id"`
	ToolID        string    `json:"tool_id"`
	Args          []byte    `json:"args"`
	OrgID         string    `json:"org_id"`
	ActingUserUid string    `json:"acting_user_uid"`
	Description   string    `json:"description"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) UpsertPendingConfirmation(ctx context.Context, arg UpsertPendingConfirmationParams) error {
	_, err := q.db.Exec(ctx, upsertPendingConfirmation,
		arg.ChatID,
		arg.ToolID,
		arg.Args,
		arg.OrgID,
		arg.ActingUserUid,
		arg.Description,
		arg.ExpiresAt,
	)
	return err
}

const upsertWaVoiceNote = `-- name: UpsertWaVoiceNote :exec

INSERT INTO wa_voice_notes (id, chat_id, direction, sender, receiver, object_path, mime_type, size_bytes, duration_seconds, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending')
ON CONFLICT (id) DO NOTHING
`

type UpsertWaVoiceNoteParams struct {
	ID              string `json:"id"`
	ChatID          string `json:"chat_id"`
	Direction       string `json:"direction"`
	Sender          string `json:"sender"`
	Receiver        string `json:"receiver"`
	ObjectPath      string `json:"object_path"`
	MimeType        string `json:"mime_type"`
	SizeBytes       int64  `json:"size_bytes"`
	DurationSeconds int32  `json:"duration_seconds"`
}

// Voice-note archive (Firebase Cloud Storage ledger) ------------------------
// ON CONFLICT DO NOTHING makes enqueueing idempotent: re-processing the same
// WhatsApp message never creates a second upload job.
func (q *Queries) UpsertWaVoiceNote(ctx context.Context, arg UpsertWaVoiceNoteParams) error {
	_, err := q.db.Exec(ctx, upsertWaVoiceNote,
		arg.ID,
		arg.ChatID,
		arg.Direction,
		arg.Sender,
		arg.Receiver,
		arg.ObjectPath,
		arg.MimeType,
		arg.SizeBytes,
		arg.DurationSeconds,
	)
	return err
}
