// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
	"time"
)

type Querier interface {
	// ClaimCollecting mirrors ClaimPendingConfirmation exactly, atomically
	// transitioning 'collecting' -> 'collecting_claimed' so two concurrent
	// inbound messages for the same chat can't both resume the same round.
	ClaimCollecting(ctx context.Context, chatID string) (PendingConfirmation, error)
	// ClaimPendingConfirmation atomically transitions a chat's pending row to
	// 'executing' and returns it. Because the UPDATE matches only status='pending',
	// exactly one of two concurrent resolvers wins the row; the loser gets no row.
	// This is the guard against double-executing a confirmed (financial) tool.
	ClaimPendingConfirmation(ctx context.Context, chatID string) (PendingConfirmation, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateConversationTurn(ctx context.Context, arg CreateConversationTurnParams) (ConversationTurn, error)
	CreateOrUpdateWaContact(ctx context.Context, arg CreateOrUpdateWaContactParams) (WaContact, error)
	CreateSttHistory(ctx context.Context, arg CreateSttHistoryParams) error
	CreateToolExecution(ctx context.Context, arg CreateToolExecutionParams) error
	CreateTtsHistory(ctx context.Context, arg CreateTtsHistoryParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWaActivity(ctx context.Context, arg CreateWaActivityParams) error
	CreateWaMessage(ctx context.Context, arg CreateWaMessageParams) error
	CreateWebhookLog(ctx context.Context, arg CreateWebhookLogParams) error
	DeletePendingConfirmation(ctx context.Context, chatID string) error
	GetAgent(ctx context.Context, id string) (Agent, error)
	GetConversationState(ctx context.Context, chatID string) (ConversationState, error)
	GetPendingConfirmation(ctx context.Context, chatID string) (PendingConfirmation, error)
	GetSettings(ctx context.Context) (Setting, error)
	GetSttHistory(ctx context.Context, limit int32) ([]SttHistory, error)
	GetTtsHistory(ctx context.Context, limit int32) ([]TtsHistory, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWaContact(ctx context.Context, chatID string) (WaContact, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListConversationTurnsAfter(ctx context.Context, arg ListConversationTurnsAfterParams) ([]ConversationTurn, error)
	ListPendingWaVoiceNotes(ctx context.Context, limit int32) ([]WaVoiceNote, error)
	ListPublishedAgents(ctx context.Context) ([]Agent, error)
	ListRecentWaActivity(ctx context.Context, limit int32) ([]WaActivity, error)
	ListWaChatsSummary(ctx context.Context) ([]ListWaChatsSummaryRow, error)
	ListWaContacts(ctx context.Context) ([]WaContact, error)
	ListWaMessagesByChat(ctx context.Context, arg ListWaMessagesByChatParams) ([]WaMessage, error)
	MarkMessageProcessed(ctx context.Context, id string) (string, error)
	// Failure keeps the row 'pending' (retryable) until attempts reaches the cap,
	// then flips it to the terminal 'failed'. next_attempt_at carries the
	// caller-computed exponential backoff.
	MarkWaVoiceNoteFailed(ctx context.Context, arg MarkWaVoiceNoteFailedParams) error
	MarkWaVoiceNoteUploaded(ctx context.Context, id string) error
	PurgeConversationTurnsBefore(ctx context.Context, ts time.Time) error
	PurgeExpiredConfirmations(ctx context.Context, expiresAt time.Time) error
	PurgeProcessedMessagesBefore(ctx context.Context, processedAt time.Time) error
	PurgeSttHistoryBefore(ctx context.Context, ts time.Time) error
	PurgeToolExecutionsBefore(ctx context.Context, ts time.Time) error
	PurgeTtsHistoryBefore(ctx context.Context, ts time.Time) error
	PurgeWaVoiceNotesBefore(ctx context.Context, createdAt time.Time) error
	RedactWaActivityBefore(ctx context.Context, ts time.Time) error
	RedactWaMessagesBefore(ctx context.Context, createdAt time.Time) error
	// last_published is stamped only on the draft->published transition (D4);
	// the CASE reads the pre-update status, per UPDATE..SET semantics. The panel
	// now edits the full five-block config, so every operator-editable column is set.
	UpdateAgentWorkflow(ctx context.Context, arg UpdateAgentWorkflowParams) (Agent, error)
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error
	UpdateWaContactSettings(ctx context.Context, arg UpdateWaContactSettingsParams) (WaContact, error)
	// UpsertCollecting parks a tool call that is still missing required args
	// (F-1 fix). Mirrors UpsertPendingConfirmation's upsert shape exactly, but
	// with status='collecting' and the extra slot-filling columns populated.
	UpsertCollecting(ctx context.Context, arg UpsertCollectingParams) error
	UpsertConversationState(ctx context.Context, arg UpsertConversationStateParams) error
	UpsertPendingConfirmation(ctx context.Context, arg UpsertPendingConfirmationParams) error
	// Voice-note archive (Firebase Cloud Storage ledger) ------------------------
	// ON CONFLICT DO NOTHING makes enqueueing idempotent: re-processing the same
	// WhatsApp message never creates a second upload job.
	UpsertWaVoiceNote(ctx context.Context, arg UpsertWaVoiceNoteParams) error
}

var _ Querier = (*Queries)(nil)
